# Generated by Django 4.1.6 on 2023-02-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_remove_cartitem_quantity_remove_orderitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Score'),
        ),
    ]
